### ISSUE TITLE
Allied banners not showing up

### ISSUE THREAD

**Issue by Kinjo878** [SebLavK/BearMyBanner#3]
In the experimental version allied banners are not showing up in battle. The banners on your troops do and the enemies but none of the allies on your side.

**Comment by SebLavK** [comment]
Thanks for posting the bug here.

I've completely changed how the mod assigns banners. Previously it ran through lists of units the game defines as "teams", but that had some problems. Each team can be made of several parties. There are also "allied teams" which I've never seen being used. Then again, I haven't tested all scenarios.

With the last changes it keeps track of every unit that spawns, as well as its type and party (so now it also gives banners to troops that spawn mid battle, two birds with one stone) and gives it a banner or not. I think this will fix the bug, I will release a new version in a few hours.

In any case, could you tell me more details about this? Are you in an army when this happens? Are you the leader of said army? Or are you getting into a battle when a friendly party is close by so it gets involved in your fight?

**Comment by Kinjo878** [comment]
I was checking out the thread again and saw you had a Github and knew you were the real deal :P

As far as the issue goes I was traveling and joined a battle that had a common enemy. Looking forward to the update and will test it out and report back what I find.

**Comment by SebLavK** [comment]
Just uploaded the new version, it should do the trick. Let me know if it still happens, or something new comes up.

Really, thanks a lot for taking the time to give some feedback :)

**Comment by Kinjo878** [comment]
Nice work! I'll give it a spin.
