### ISSUE TITLE
Cavarly dropping banners at the start of battles

### ISSUE THREAD

**Issue by Kinjo878** [SebLavK/BearMyBanner#4]
I notice the latest experimental version cavalry units are dropping their banners at the start of a battle. It seems to happen to allied and enemy cav units.

**Comment by SebLavK** [comment]
Yes, this is part of the game AI. Why would you hold a banner when you have a nice protective shield or a shiny destructive two handed weapon? It's why I take away bows from ranged units.

I'm not sure why it happens now. Since I changed the inner workings, units are given banners before they are deployed instead of after.

The easy solution would be to take away their items like with archers, but I'll see if I can have them keep them while using the banner. In the future I'd like to make them drop their banners under some situations like when falling off the horse or being surrounded, and it would be nice if they could reach for their original shield.

**Comment by SebLavK** [comment]
Ok, there is definitely something going on between units being built and units being assigned to a formation.

I used the latter to insert my mod in previous version, but it wouldn't work for newer waves of enemies. Since v0.5.2 I'm using the built phase, which should work for every spawn, but they drop the banner while they're being assigned to a formation.

If I could find that moment and insert my mod there we should have the best of both worlds.

**Comment by SebLavK** [comment]
Found the culprit. `Mission` class has a `SpawnTroop` that accepts the flag `wieldInitialWeapons`. The mission spawn logic behaviour always sends this flag (I guess if it didn't troops would start with with bare hands).

Now to see how to make them keep wielding the banner, instead of wielding their original shield or whatever and hence dropping the banner.

**Comment by SebLavK** [comment]
Fixed in the newest version! ^^

**Comment by Kinjo878** [comment]
Excellent work man! I got to say I have worked on mods for years and you are killing it brother!

**Comment by SebLavK** [comment]
Thanks!

I'd definitely like to keep this mod relevant once banners are back natively. I'll play around with banners in tournaments next, but after that I'm interested in seeing if I can play around with formation banners where you could use the online banner editor to have custom banners for infantry, skirmishers, archers, heavy infantry, etc. (each of the 8 formations you can set in the party menu)
